---
title: "09_cluster_and_immune"
author: "Yuqing Li"
date: "2025-05-21"
output: html_document
---

### Load requirements
```{r, message=FALSE,warning=FALSE}
{
  library(GSVA)
  library(ggpubr)
  library(tidyr)
  library(dplyr)
  library(magrittr)
  library(Biobase)
  library(stringr)
  library(IOBR)
  library(clusterProfiler)
  library(ComplexHeatmap)
  library(circlize)
  library(openxlsx)
  library(ggunchained)
}
thm <- theme_bw()+
  theme(panel.border = element_rect(),
        panel.grid.major = element_blank(),   
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black",size=0.5),
        text = element_text(size = 20),
        axis.text.x = element_text(size=25,color ='black'),
        axis.text.y = element_text(size = 20,color = 'black'),
        axis.title.y = element_text(size = 20),
        plot.subtitle  = element_text(face = 'italic',hjust = 0.5),
        legend.position='right',
        legend.text = element_text(size = 15,hjust = 0),
        legend.title = element_text(size = 20)
  )

```

### Load data
```{r, message=FALSE,warning=FALSE}

# gene expression
gene_tpm <- read.xlsx( './00_data_preparation/gene_table.xlsx',sheet = 1,rowNames = TRUE) %>%  mutate_all(as.numeric);dim(gene_tpm)

# clinical data
df_meta_acc_tcga <- read.csv("./00_data_preparation/metadata.csv",na.strings = "") %>% dplyr::filter(COHORT=='TCGA')

df_cluster_clinical <- read.csv("./clustering/whole/pam/Unsupervised_clustering.csv") %>% 
  dplyr::select(c("PATIENT_ID", "genus_tcga_s_euclidean")) %>% 
  setNames(c("PATIENT_ID", "MS")) %>% 
  dplyr::mutate(MS=recode(.$MS,'1'="MS1",'2'="MS2")) %>% 
  dplyr::mutate(MS = as.factor(MS)) %>% 
  merge(., df_meta_acc_tcga, by="PATIENT_ID", all = TRUE) %>% 
  set_rownames(.$PATIENT_ID)
```

### Microbial clustering and immune score
```{r, message=FALSE,warning=FALSE}
fun_tme_score <- function(exp){
  
  # exp: gene*sample, data.frame
  
  # cibersort
  ciber_res<-deconvo_tme(eset = exp, method = "cibersort", arrays = FALSE, perm = 100 )

  # epic
  epic_res <- deconvo_tme(eset = exp, method = "epic", arrays = FALSE)
  
  # quantiseq
  quantiseq_res <- deconvo_tme(eset = exp, tumor = F, arrays = FALSE, scale_mrna = TRUE, method = "quantiseq")
  
  # mcpcounter
  mcpcounter_res <- deconvo_tme(eset = exp, method = "mcpcounter")
  
  # xcell
  xcell_res <- deconvo_tme(eset = exp, method = "xcell",arrays = FALSE)
  
  # estimate
  estimate_res <- deconvo_tme(eset = exp, method = "estimate")
  
  # ips
  ips_res <- deconvo_tme(eset = exp, method = "ips", plot= F)
  
  # gsva
  gene_set<-read.csv("./source_data/gsva_immune_cells.csv")[, 1:2]
  #https://www.cell.com/cms/10.1016/j.celrep.2016.12.019/attachment/f353dac9-4bf5-4a52-bb9a-775e74d5e968/mmc3.xlsx
  gene_set_list<- split(as.matrix(gene_set)[,1], gene_set[,2])
  gsvaPar <- gsvaParam(as.matrix(exp), gene_set_list,maxDiff = TRUE)
  immu_cells_res <- gsva(gsvaPar) %>% 
    t() %>% 
    as.data.frame() %>% 
    set_colnames(paste0(colnames(.),'_customed')) %>% 
    tibble::rownames_to_column('ID')

  # result above all
  res_all <- Reduce(function(x, y) merge(x, y, by = "ID"),
                    list(ciber_res[,-24:-26],epic_res,quantiseq_res,mcpcounter_res,xcell_res,estimate_res,ips_res,immu_cells_res))
  
  return(res_all)
}
res_tme <- fun_tme_score(gene_tpm)
df_cluster_clinical_tme <- merge(df_cluster_clinical,res_tme,by.x='PATIENT_ID',by.y='ID')

# heatmap plot
fun_heatmap_immune_score <- function(df_cluster_clinical_tme){
  
  data <- df_cluster_clinical_tme %>% 
    dplyr::select("PATIENT_ID", contains(c('EPIC','quantiseq','MCPcounter','IPS','customed'))) %>%
    tibble::column_to_rownames('PATIENT_ID') %>% 
    t() 
  pd1 <- df_cluster_clinical_tme %>% 
    dplyr::select("PATIENT_ID", 'MS') %>% 
    dplyr::mutate(MS=factor(.$MS,levels=c('MS1','MS2')))
  pd2 <- data.frame(immue_score=rownames(data),immue_type=c(rep('EPIC',sum(str_detect(rownames(data),'_EPIC'))),
                                                            rep('quantiseq',sum(str_detect(rownames(data),'_quantiseq'))),
                                                            rep('MCPcounter',sum(str_detect(rownames(data),'_MCPcounter'))),
                                                            rep('IPS',sum(str_detect(rownames(data),'_IPS'))),
                                                            rep('customed',sum(str_detect(rownames(data),'_customed')))))
  
  setequal(pd1$PATIENT_ID,colnames(data))
  
  data_nor <- scale(t(data)) %>%  
    t() %>% 
    as.data.frame() %>% 
    dplyr::mutate(across(everything(), ~ ifelse(. > 1, 1, .))) %>% 
    dplyr::mutate(across(everything(), ~ ifelse(. < -1, -1, .)))
  # boxplot(data_nor);range(data_nor)
  
  group <- pd1$MS
  test_results <- apply(data_nor, 1, function(row) {
    group1_values <- row[group == "MS1"]
    group2_values <- row[group == "MS2"]
    test <-wilcox.test(group1_values, group2_values)
    test$p.value
  })
  
  significance_group <- ifelse(test_results < 0.05, "Significant", "Not Significant")
  row_annotation <- rowAnnotation(p_value = anno_barplot(-log10(test_results)),
                                  signif = significance_group,
                                  col=list(signif=c("Significant" = "red", "Not Significant" = "#eaebea")))
  
  color_fun <- colorRamp2(c(1,0,-1), c("#FFFF00", "white", "#2D004B"))
  # color_fun <- colorRamp2(c(1,0.25,0,-0.25,-1), c(c('#08306C','#4778A9','#68AAD1','#9FC7E0','#C9DBEA')))
  column_annotation <- HeatmapAnnotation(MS = pd1$MS,
                                         col = list(MS = c("MS1" = "#0072B5CC", "MS2" = "#E18727CC")))
  
  p <- ComplexHeatmap::Heatmap(data_nor, 
                          na_col = "white",
                          col = color_fun,  
                          show_column_names = F,
                          row_names_side = "right",
                          name = "fraction",
                          column_split = pd1$MS, 
                          column_gap = unit(5, "mm"),
                          row_split = pd2$immue_type,
                          row_gap = unit(8, "mm"),
                          column_title = NULL,
                          cluster_columns = TRUE,
                          cluster_rows = F, 
                          top_annotation = column_annotation,
                          right_annotation = row_annotation,
                          width = ncol(data_nor)*unit(3, "mm"), 
                          height = nrow(data_nor)*unit(3, "mm"),
                          row_names_gp = gpar(fontsize = 8) 
  )
  return(p)
}

# pdf('./cluster_and_immune/heatmap_cluster_and_immune.pdf',width = 15,height = 15)
p <- fun_heatmap_immune_score(df_cluster_clinical_tme)
print(p)
# dev.off()

# ggplot
data <- df_cluster_clinical_tme %>% dplyr::select("PATIENT_ID", "MS",'CD56bright natural killer cell_customed','Memory B cell_customed') 
# pdf('./cluster_and_immune/ggplot_cluster_and_immune.pdf',width = 5,height = 5)
ggplot(data,aes(x=MS,y=`CD56bright natural killer cell_customed`,fill=MS))+
  geom_jitter(shape=16, color="grey",size=2.0,position=position_jitter(0.2))+
  geom_violin()+
  stat_summary(fun = mean,
               fun.min = function(x){quantile(x)[2]},
               fun.max = function(x){quantile(x)[4]},
               geom = "pointrange",
               size=0.5,
               position = position_dodge(width = 0.2))+
  theme_bw()+
  scale_fill_manual(values = c(MS1="#0072B5CC",MS2="#E18727CC"))+
  guides(fill=guide_legend(direction = "horizontal",nrow =1,position = 'bottom'))+
  labs(x="", y = "CD56bright natural killer cell", fill = "")+  
  stat_compare_means(method = "wilcox.test",label = "p.format",size=6)+
  thm
ggplot(data,aes(x=MS,y=`Memory B cell_customed`,fill=MS))+
  geom_jitter(shape=16, color="grey",size=2.0,position=position_jitter(0.2))+
  geom_violin()+
  stat_summary(fun = mean,
               fun.min = function(x){quantile(x)[2]},
               fun.max = function(x){quantile(x)[4]},
               geom = "pointrange",
               size=0.5,
               position = position_dodge(width = 0.2))+
  theme_bw()+
  scale_fill_manual(values = c(MS1="#0072B5CC",MS2="#E18727CC"))+
  guides(fill=guide_legend(direction = "horizontal",nrow =1,position = 'bottom'))+
  labs(x="", y = "Memory B cell", fill = "")+  
  stat_compare_means(method = "wilcox.test",label = "p.format",size=6)+
  thm
# dev.off()
```

### Microbial clusteringr and immune inhibitory genes
```{r, message=FALSE,warning=FALSE}
immuno_inhibitory_gene_matrix <- read.table(file = './source_data/immune_signature_annotation.txt',sep = '\t',header = T)
immuno_inhibitory_gene_tpm <- t(gene_tpm) %>% as.data.frame() %>% dplyr::select(any_of(immuno_inhibitory_gene_matrix$GeneSymbol)) %>% tibble::rownames_to_column('PATIENT_ID') %>% merge(df_cluster_clinical[,c('PATIENT_ID','MS')],.,by='PATIENT_ID')

data <- immuno_inhibitory_gene_tpm %>% gather(key = 'Gene',value = "Value",-PATIENT_ID,-MS)
p_values <- compare_means(Value ~ MS, data = data, group.by = "Gene", method = "wilcox.test")
significant_genes <- p_values %>%dplyr::filter(p < 0.05) %>% pull(Gene)  
data <- data %>% dplyr::filter(Gene%in%significant_genes)
# pdf('./cluster_and_immune/ggplot_cluster_and_immune_gene.pdf',width = 15,height = 4)
ggplot(data,aes(x=Gene,y=Value,fill=MS))+
  geom_jitter(shape=16, color="grey",size=2.0)+
  geom_boxplot()+
  stat_compare_means(label='p.signif',method = 'wilcox.test')+
  scale_fill_manual(values = c(MS1="#0072B5CC",MS2="#E18727CC"))+
  labs(x="", y = "Gene exp (TPM)", fill = "")+  
  thm
# dev.off()
```

