---
title: "Unsupervised_clustering"
output: html_document
date: "2023-03-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### load requirements
```{r}
# load libraries
library(ggplot2)
library(dplyr)
library(tidyverse)
library(vegan)
library(ComplexHeatmap)
library(fpc)
library(fossil)
library(ggthemes)
library(ggsci)
library(cluster)
library(corrplot)
library(survival)
library(survminer)
```


### load data
```{r}
df_meta_ACC <- read.csv("../Tables/metadata_77_ACC.csv")

# load microbial data from Poore's study
df_Voom_SNM_ACC_PCPG <- read.csv("../Tables/Voom-SNM-ACC_PCPG.csv", row.names = 1)
df_Voom_SNM_f_likely_ACC_PCPG <- read.csv("../Tables/Voom-SNM-Filter-Likely-ACC_PCPG.csv", row.names = 1)
df_Voom_SNM_f_PC_ACC_PCPG <- read.csv("../Tables/Voom-SNM-Filter-Plate_Center-ACC_PCPG.csv", row.names = 1)
df_Voom_SNM_f_putative_ACC_PCPG <- read.csv("../Tables/Voom-SNM-Filter-Putative-ACC_PCPG.csv", row.names = 1)
df_Voom_SNM_f_strigent_ACC_PCPG <- read.csv("../Tables/Voom-SNM-Filter-Stringent-ACC_PCPG.csv", row.names = 1)

df_Voom_SNM_ACC <- df_Voom_SNM_ACC_PCPG[df_meta_ACC$id,]
df_Voom_SNM_f_likely_ACC <- df_Voom_SNM_f_likely_ACC_PCPG[df_meta_ACC$id,]
df_Voom_SNM_f_PC_ACC <- df_Voom_SNM_f_PC_ACC_PCPG[df_meta_ACC$id,]
df_Voom_SNM_f_putative_ACC <- df_Voom_SNM_f_putative_ACC_PCPG[df_meta_ACC$id,]
df_Voom_SNM_f_strigent_ACC <- df_Voom_SNM_f_strigent_ACC_PCPG[df_meta_ACC$id,]

df_Voom_SNM_ACC_Vir <- df_Voom_SNM_ACC  %>% select(grep("Virus", names(df_Voom_SNM_ACC)))
df_Voom_SNM_f_likely_ACC_Vir <- df_Voom_SNM_f_likely_ACC  %>% select(grep("Virus", names(df_Voom_SNM_f_likely_ACC)))
df_Voom_SNM_f_PC_ACC_Vir <- df_Voom_SNM_f_PC_ACC  %>% select(grep("Virus", names(df_Voom_SNM_f_PC_ACC)))
df_Voom_SNM_f_putative_ACC_Vir <- df_Voom_SNM_f_putative_ACC  %>% select(grep("Virus", names(df_Voom_SNM_f_putative_ACC)))
df_Voom_SNM_f_strigent_ACC_Vir <- df_Voom_SNM_f_strigent_ACC  %>% select(grep("Virus", names(df_Voom_SNM_f_strigent_ACC)))

df_Voom_SNM_ACC_Arc <- df_Voom_SNM_ACC  %>% select(grep("Archaea", names(df_Voom_SNM_ACC)))
df_Voom_SNM_f_likely_ACC_Arc <- df_Voom_SNM_f_likely_ACC  %>% select(grep("Archaea", names(df_Voom_SNM_f_likely_ACC)))
df_Voom_SNM_f_PC_ACC_Arc <- df_Voom_SNM_f_PC_ACC  %>% select(grep("Archaea", names(df_Voom_SNM_f_PC_ACC)))
df_Voom_SNM_f_putative_ACC_Arc <- df_Voom_SNM_f_putative_ACC  %>% select(grep("Archaea", names(df_Voom_SNM_f_putative_ACC)))
df_Voom_SNM_f_strigent_ACC_Arc <- df_Voom_SNM_f_strigent_ACC  %>% select(grep("Archaea", names(df_Voom_SNM_f_strigent_ACC)))

df_Voom_SNM_ACC_Bac <- df_Voom_SNM_ACC  %>% select(grep("Bacteria", names(df_Voom_SNM_ACC)))
df_Voom_SNM_f_likely_ACC_Bac <- df_Voom_SNM_f_likely_ACC  %>% select(grep("Bacteria", names(df_Voom_SNM_f_likely_ACC)))
df_Voom_SNM_f_PC_ACC_Bac <- df_Voom_SNM_f_PC_ACC  %>% select(grep("Bacteria", names(df_Voom_SNM_f_PC_ACC)))
df_Voom_SNM_f_putative_ACC_Bac <- df_Voom_SNM_f_putative_ACC  %>% select(grep("Bacteria", names(df_Voom_SNM_f_putative_ACC)))
df_Voom_SNM_f_strigent_ACC_Bac <- df_Voom_SNM_f_strigent_ACC  %>% select(grep("Bacteria", names(df_Voom_SNM_f_strigent_ACC)))
```


### Determine the optimal number of clusters
```{r}
# compute the combined metric of BC and UU from Shi et al. (DOI: 10.1186/s40168-021-01199-3)
function_dist <- function(in_matrix, dist=c("combined", "bray", "jaccard")){
          combMetric<-function(bray,uu,alpha=0.5){
            bray<-as.matrix(bray)
            uu<-as.matrix(uu)
            bray<-bray/max(bray)
            uu<-uu/max(uu)
            combined<-(1-alpha)*bray+alpha*uu
            rownames(combined)<-rownames(bray)
            colnames(combined)<-colnames(bray)
            combined<-as.dist(combined)
            combined
          }
          in_matrix[in_matrix<0] <- 0 # assign zero to negative values 
          dist_br <- vegan::vegdist(in_matrix, method = "bray")
          dist_UU <- vegan::vegdist(in_matrix, method = "jaccard")
          dist_com <- combMetric(dist_br, dist_UU, alpha=0.5)
          if (dist=="combined"){return(dist_com)}
          else if (dist=="bray"){return(dist_br)}
          else {return(dist_UU)}
}

# determine the optimal number of clusters using different distance
function_optimal <- function(df1, df2, df3, df4, df5, dist=c("combined", "bray", "jaccard")){
      if (dist=="combined"){
        dist_nor_com <- function_dist(df1, dist = "combined")
        dist_nor_likely_com <- function_dist(df2, dist = "combined")
        dist_nor_PC_com <- function_dist(df3, dist = "combined")
        dist_nor_putative_com <- function_dist(df4, dist = "combined")
        dist_nor_strigent_com <- function_dist(df5, dist = "combined")
      }else if (dist=="bray"){
        dist_nor_com <- function_dist(df1, dist = "bray")
        dist_nor_likely_com <- function_dist(df2, dist = "bray")
        dist_nor_PC_com <- function_dist(df3, dist = "bray")
        dist_nor_putative_com <- function_dist(df4, dist = "bray")
        dist_nor_strigent_com <- function_dist(df5, dist = "bray")
      }else{
        dist_nor_com <- function_dist(df1, dist = "jaccard")
        dist_nor_likely_com <- function_dist(df2, dist = "jaccard")
        dist_nor_PC_com <- function_dist(df3, dist = "jaccard")
        dist_nor_putative_com <- function_dist(df4, dist = "jaccard")
        dist_nor_strigent_com <- function_dist(df5, dist = "jaccard")
      }

      function_assess <- function(in_dist, id){
        df_si <- data.frame()
        # Average silhouette width
        for (k in 2:10){
          pam_x <- pam(in_dist, k, diss=TRUE, keep.diss=FALSE, keep.data=FALSE)
          df_temp <- data.frame(ncluster=k, silinfo=pam_x$silinfo$avg.width)
          df_si <- rbind(df_si, df_temp)
        }
        # Prediction strength
        ps <- prediction.strength(in_dist, Gmin=2, Gmax=10, clustermethod=claraCBI, classification="centroid", distances=TRUE)
        df_ps <- data.frame(ncluster=1:10, predictionS=ps$mean.pred)
        df_m <- merge(df_si, df_ps, by="ncluster", all.x = TRUE)
        df_m$class <- id
        return(df_m)
  }
  
  df_ass_nor <- function_assess(dist_nor_com, "Nor")
  df_ass_nor_f_likely <- function_assess(dist_nor_likely_com, "F_likely")
  df_ass_nor_f_PC <- function_assess(dist_nor_PC_com, "F_PC")
  df_ass_nor_f_putative <- function_assess(dist_nor_putative_com, "F_putative")
  df_ass_nor_f_strigent <- function_assess(dist_nor_strigent_com, "F_strigent")
  
  df_ass_bind <- rbind(df_ass_nor, df_ass_nor_f_likely, df_ass_nor_f_PC, df_ass_nor_f_putative, df_ass_nor_f_strigent)
  df_ass_bind_melt <- reshape2::melt(df_ass_bind, id=c("ncluster", "class"))
  df_ass_bind_melt$variable <- as.character(df_ass_bind_melt$variable)
  df_ass_bind_melt$variable[df_ass_bind_melt$variable=="silinfo"] <- "Average silhouette width"
  df_ass_bind_melt$variable[df_ass_bind_melt$variable=="predictionS"] <- "Prediction Strength"
  
  p_ass <- ggplot(df_ass_bind_melt, aes(x=ncluster)) + 
    geom_point(aes(y = value, color=class), size=2)+
    geom_line(aes(y = value, color=class))+
    facet_wrap(~ variable, ncol = 2)+
    theme_bw()+
    scale_color_npg()+
    theme(strip.text=element_text())+
    xlab("Number of clusters")+
    ylab("")
  return(p_ass)
}

p_cluster_overall_com <-  function_optimal(df_Voom_SNM_ACC, df_Voom_SNM_f_likely_ACC, df_Voom_SNM_f_PC_ACC,
                                            df_Voom_SNM_f_putative_ACC, df_Voom_SNM_f_strigent_ACC, dist="combined")
p_cluster_virus_com <-  function_optimal(df_Voom_SNM_ACC_Vir, df_Voom_SNM_f_likely_ACC_Vir, df_Voom_SNM_f_PC_ACC_Vir,
                                          df_Voom_SNM_f_putative_ACC_Vir, df_Voom_SNM_f_strigent_ACC_Vir, dist="combined")
p_cluster_archaea_com <-  function_optimal(df_Voom_SNM_ACC_Arc, df_Voom_SNM_f_likely_ACC_Arc, df_Voom_SNM_f_PC_ACC_Arc,
                                            df_Voom_SNM_f_putative_ACC_Arc, df_Voom_SNM_f_strigent_ACC_Arc, dist="combined")
p_cluster_bacteria_com <-  function_optimal(df_Voom_SNM_ACC_Bac, df_Voom_SNM_f_likely_ACC_Bac, df_Voom_SNM_f_PC_ACC_Bac,
                                             df_Voom_SNM_f_putative_ACC_Bac, df_Voom_SNM_f_strigent_ACC_Bac, dist="combined")

p_cluster_overall_br <-  function_optimal(df_Voom_SNM_ACC, df_Voom_SNM_f_likely_ACC, df_Voom_SNM_f_PC_ACC,
                                           df_Voom_SNM_f_putative_ACC, df_Voom_SNM_f_strigent_ACC, dist="bray")
p_cluster_virus_br <-  function_optimal(df_Voom_SNM_ACC_Vir, df_Voom_SNM_f_likely_ACC_Vir, df_Voom_SNM_f_PC_ACC_Vir,
                                         df_Voom_SNM_f_putative_ACC_Vir, df_Voom_SNM_f_strigent_ACC_Vir, dist="bray")
p_cluster_archaea_br <-  function_optimal(df_Voom_SNM_ACC_Arc, df_Voom_SNM_f_likely_ACC_Arc, df_Voom_SNM_f_PC_ACC_Arc,
                                           df_Voom_SNM_f_putative_ACC_Arc, df_Voom_SNM_f_strigent_ACC_Arc, dist="bray")
p_cluster_bacteria_br <-  function_optimal(df_Voom_SNM_ACC_Bac, df_Voom_SNM_f_likely_ACC_Bac, df_Voom_SNM_f_PC_ACC_Bac,
                                            df_Voom_SNM_f_putative_ACC_Bac, df_Voom_SNM_f_strigent_ACC_Bac, dist="bray")

p_cluster_overall_ja <-  function_optimal(df_Voom_SNM_ACC, df_Voom_SNM_f_likely_ACC, df_Voom_SNM_f_PC_ACC,
                                          df_Voom_SNM_f_putative_ACC, df_Voom_SNM_f_strigent_ACC, dist="jaccard")
p_cluster_virus_ja <-  function_optimal(df_Voom_SNM_ACC_Vir, df_Voom_SNM_f_likely_ACC_Vir, df_Voom_SNM_f_PC_ACC_Vir,
                                        df_Voom_SNM_f_putative_ACC_Vir, df_Voom_SNM_f_strigent_ACC_Vir, dist="jaccard")
p_cluster_archaea_ja <-  function_optimal(df_Voom_SNM_ACC_Arc, df_Voom_SNM_f_likely_ACC_Arc, df_Voom_SNM_f_PC_ACC_Arc,
                                          df_Voom_SNM_f_putative_ACC_Arc, df_Voom_SNM_f_strigent_ACC_Arc, dist="jaccard")
p_cluster_bacteria_ja <-  function_optimal(df_Voom_SNM_ACC_Bac, df_Voom_SNM_f_likely_ACC_Bac, df_Voom_SNM_f_PC_ACC_Bac,
                                           df_Voom_SNM_f_putative_ACC_Bac, df_Voom_SNM_f_strigent_ACC_Bac, dist="jaccard")

# pdf(file = "Figures/Determine_optimal_cluster_number_Voom-SNM.pdf", width = 7, height = 4)
p_cluster_overall_com + ggtitle("Overall_Combined")
p_cluster_virus_com + ggtitle("Virus_Combined")
p_cluster_archaea_com + ggtitle("Archaea_Combined")
p_cluster_bacteria_com + ggtitle("Bacteria_Combined")
p_cluster_overall_br + ggtitle("Overall_Bray")
p_cluster_virus_br + ggtitle("Virus_Bray")
p_cluster_archaea_br + ggtitle("Archaea_Bray")
p_cluster_bacteria_br + ggtitle("Bacteria_Bray")
p_cluster_overall_ja + ggtitle("Overall_jaccard")
p_cluster_virus_ja + ggtitle("Virus_jaccard")
p_cluster_archaea_ja + ggtitle("Archaea_jaccard")
p_cluster_bacteria_ja + ggtitle("Bacteria_jaccard")
# dev.off()
```


### Check association between cluster and survival
```{r}
function_sur <- function(in_matrix, dist_s=c("combined", "bray", "jaccard")){
                dist_in <- function_dist(in_matrix, dist=dist_s)
                # group into 2 cluster
                pam_x <- pam(as.matrix(dist_in), 2, diss=TRUE, keep.diss=FALSE, keep.data=FALSE)
                
                df_cluster <- pam_x$clustering %>% as.data.frame() %>% setNames("Cluster_PAM")
                df_cluster$id <- rownames(df_cluster)
                
                df_meta_ACC_m <- merge(df_meta_ACC[, c("id", "OS_MONTHS", "CENSOR")], df_cluster, by="id", all.x = TRUE)

                fit <- survfit(Surv(OS_MONTHS, CENSOR) ~ Cluster_PAM, data = df_meta_ACC_m)
                
                p <- ggsurvplot(fit,
                                data = df_meta_ACC_m,
                                conf.int = TRUE,
                                pval = TRUE,
                                palette = c("#0072B5CC","#E18727CC"),
                                xlab = "Time (Monthes)", 
                                legend = "right",
                                legend.title = "",
                                ggtheme = theme_base(),
                                break.x.by = 40)
                return(list(df_meta_ACC_m, p))
}

df_cluster_overall <- data.frame()
for (x in c("combined", "bray", "jaccard")){
  #x = "combined"
  list_nor <- function_sur(df_Voom_SNM_ACC, dist = x)
  list_nor_f_likely <- function_sur(df_Voom_SNM_f_likely_ACC, dist = x)
  list_nor_f_PC <- function_sur(df_Voom_SNM_f_PC_ACC, dist = x)
  list_nor_f_putative <- function_sur(df_Voom_SNM_f_putative_ACC, dist = x)
  list_nor_f_strigent <- function_sur(df_Voom_SNM_f_strigent_ACC, dist = x)
  list_Vir_nor <- function_sur(df_Voom_SNM_ACC_Vir, dist = x)
  list_Vir_nor_f_likely <- function_sur(df_Voom_SNM_f_likely_ACC_Vir, dist = x)
  list_Vir_nor_f_PC <- function_sur(df_Voom_SNM_f_PC_ACC_Vir, dist = x)
  list_Vir_nor_f_putative <- function_sur(df_Voom_SNM_f_putative_ACC_Vir, dist = x)
  list_Vir_nor_f_strigent <- function_sur(df_Voom_SNM_f_strigent_ACC_Vir, dist = x)
  list_Arc_nor <- function_sur(df_Voom_SNM_ACC_Arc, dist = x)
  list_Arc_nor_f_likely <- function_sur(df_Voom_SNM_f_likely_ACC_Arc, dist = x)
  list_Arc_nor_f_PC <- function_sur(df_Voom_SNM_f_PC_ACC_Arc, dist = x)
  list_Arc_nor_f_putative <- function_sur(df_Voom_SNM_f_putative_ACC_Arc, dist = x)
  list_Arc_nor_f_strigent <- function_sur(df_Voom_SNM_f_strigent_ACC_Arc, dist = x)
  list_Bac_nor <- function_sur(df_Voom_SNM_ACC_Bac, dist = x)
  list_Bac_nor_f_likely <- function_sur(df_Voom_SNM_f_likely_ACC_Bac, dist = x)
  list_Bac_nor_f_PC <- function_sur(df_Voom_SNM_f_PC_ACC_Bac, dist = x)
  list_Bac_nor_f_putative <- function_sur(df_Voom_SNM_f_putative_ACC_Bac, dist = x)
  list_Bac_nor_f_strigent <- function_sur(df_Voom_SNM_f_strigent_ACC_Bac, dist = x)
  
  # pdf(file = paste("Figures/Determine_Clustering_AND_Survival_Voom-SNM_",x,".pdf", sep = ""), width = 6, height = 4)
  print(list_nor[[2]] + ggtitle("Overall_Nor"))
  print(list_nor_f_likely[[2]] + ggtitle("Overall_Nor_likely"))
  print(list_nor_f_PC[[2]] + ggtitle("Overall_Nor_PC"))
  print(list_nor_f_putative[[2]] + ggtitle("Overall_Nor_putative"))
  print(list_nor_f_strigent[[2]] + ggtitle("Overall_Nor_strigent"))
  print(list_Vir_nor[[2]] + ggtitle("Overall_Nor_Virus"))
  print(list_Vir_nor_f_likely[[2]] + ggtitle("Overall_Nor_likely_Virus"))
  print(list_Vir_nor_f_PC[[2]] + ggtitle("Overall_Nor_PC_Virus"))
  print(list_Vir_nor_f_putative[[2]] + ggtitle("Overall_Nor_putative_Virus"))
  print(list_Vir_nor_f_strigent[[2]] + ggtitle("Overall_Nor_strigent_Virus"))
  print(list_Arc_nor[[2]] + ggtitle("Overall_Nor_Archaea"))
  print(list_Arc_nor_f_likely[[2]] + ggtitle("Overall_Nor_likely_Archaea"))
  print(list_Arc_nor_f_PC[[2]] + ggtitle("Overall_Nor_PC_Archaea"))
  print(list_Arc_nor_f_putative[[2]] + ggtitle("Overall_Nor_putative_Archaea"))
  print(list_Arc_nor_f_strigent[[2]] + ggtitle("Overall_Nor_strigent_Archaea"))
  print(list_Bac_nor[[2]] + ggtitle("Overall_Nor_Bacteria"))
  print(list_Bac_nor_f_likely[[2]] + ggtitle("Overall_Nor_likely_Bacteria"))
  print(list_Bac_nor_f_PC[[2]] + ggtitle("Overall_Nor_PC_Bacteria"))
  print(list_Bac_nor_f_putative[[2]] + ggtitle("Overall_Nor_putative_Bacteria"))
  print(list_Bac_nor_f_strigent[[2]] + ggtitle("Overall_Nor_strigent_Bacteria"))
  # dev.off()
  
  df_nor <- list_nor[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Without_",x,sep = "")))
  df_nor_f_likey <- list_nor_f_likely[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Likely_", x,sep = "")))
  df_nor_f_PC <- list_nor_f_PC[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("PC_",x,sep = "")))
  df_nor_f_putative <- list_nor_f_putative[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Putative_",x,sep = "")))
  df_nor_f_strigent <- list_nor_f_strigent[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Strigent_",x,sep = "")))
  df_nor_Vir <- list_Vir_nor[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Without_Vir_",x,sep = "")))
  df_nor_f_likey_Vir <- list_Vir_nor_f_likely[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Likely_Vir_",x,sep = "")))
  df_nor_f_PC_Vir <- list_Vir_nor_f_PC[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("PC_Vir_",x,sep = "")))
  df_nor_f_putative_Vir <- list_Vir_nor_f_putative[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Putative_Vir_",x,sep = "")))
  df_nor_f_strigent_Vir <- list_Vir_nor_f_strigent[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Strigent_Vir_",x,sep = "")))
  df_nor_Arc <- list_Arc_nor[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Without_Arc_",x,sep = "")))
  df_nor_f_likey_Arc <- list_Arc_nor_f_likely[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Likely_Arc_",x,sep = "")))
  df_nor_f_PC_Arc <- list_Arc_nor_f_PC[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("PC_Arc_",x,sep = "")))
  df_nor_f_putative_Arc <- list_Arc_nor_f_putative[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Putative_Arc_",x,sep = "")))
  df_nor_f_strigent_Arc <- list_Arc_nor_f_strigent[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Strigent_Arc_",x,sep = "")))
  df_nor_Bac <- list_Bac_nor[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Without_Bac_",x,sep = "")))
  df_nor_f_likey_Bac <- list_Bac_nor_f_likely[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Likely_Bac_",x,sep = "")))
  df_nor_f_PC_Bac <- list_Bac_nor_f_PC[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("PC_Bac_",x,sep = "")))
  df_nor_f_putative_Bac <- list_Bac_nor_f_putative[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Putative_Bac_",x,sep = "")))
  df_nor_f_strigent_Bac <- list_Bac_nor_f_strigent[[1]] %>% dplyr::select(c("id", "Cluster_PAM")) %>% setNames(c("id", paste("Strigent_Bac_",x,sep = "")))
  
  df_clustering <- Reduce(function(x,y){merge(x,y,by="id", all.x=TRUE)},
                          list(df_nor, df_nor_f_likey, df_nor_f_PC, df_nor_f_putative, df_nor_f_strigent,
                               df_nor_Vir, df_nor_f_likey_Vir, df_nor_f_PC_Vir, df_nor_f_putative_Vir,
                               df_nor_Arc, df_nor_f_likey_Arc, df_nor_f_PC_Arc, df_nor_f_putative_Arc,
                               df_nor_Bac, df_nor_f_likey_Bac, df_nor_f_PC_Bac, df_nor_f_putative_Bac, df_nor_f_strigent_Bac))
  if (dim(df_cluster_overall)[1]==0){
    df_cluster_overall <- df_clustering
  }else{
    df_cluster_overall <- merge(df_cluster_overall, df_clustering, by="id", all.x=TRUE)
  }
  }

write.csv(df_cluster_overall, file="../Tables/Unspervised_clustering.csv", row.names = FALSE)
```


### Comparing clusters among different levels of filter
```{r}
function_rand <- function(in_matrix, type_s=c("full", "lower", "upper"), add_text = NULL){
  df_adj.index <- data.frame()
  for (x in 1:(ncol(in_matrix))) {
    # compute Adjusted Rand Index
    for (y in 1:ncol(in_matrix)){
      adj.index <- fossil::adj.rand.index(in_matrix[,x], in_matrix[,y])
      id_1 <- names(in_matrix)[x]
      id_2 <- names(in_matrix)[y]
      df_temp <- data.frame(c1=id_1, c2=id_2, adj.rand.index=adj.index)
      df_adj.index <- rbind(df_adj.index, df_temp)
    }
  }
  
  df_adj.index_dcast <- reshape2::dcast(df_adj.index, c1~c2, value.var = "adj.rand.index")
  df_adj.index_dcast <- df_adj.index_dcast %>% remove_rownames %>% column_to_rownames(var="c1")
  name_order <- names(in_matrix)[order(names(in_matrix))]
  df_adj.index_dcast <- df_adj.index_dcast[name_order, name_order]
  if (is.null(add_text)){
    p <- {corrplot(corr=as.matrix(df_adj.index_dcast), type=type_s, col.lim = c(0,1))
      recordPlot()}
  }else{
    p <- {corrplot(corr=as.matrix(df_adj.index_dcast), type=type_s, col.lim = c(0,1), addCoef.col = "grey")
      recordPlot()}
  }
  
  return(p)
}


df_overll_cluster <- df_cluster_overall %>% dplyr::select(c("Without_combined", "Likely_combined", "PC_combined", "Putative_combined", "Strigent_combined",
                                                "Without_bray", "Likely_bray", "PC_bray", "Putative_bray", "Strigent_bray",
                                                "Without_jaccard", "Likely_jaccard", "PC_jaccard", "Putative_jaccard", "Strigent_jaccard"))
df_overll_cluster_combined <- df_cluster_overall %>% dplyr::select(c("Without_combined", "Likely_combined", "PC_combined", "Putative_combined", "Strigent_combined"))

p_all <- function_rand(df_cluster_overall[,names(df_cluster_overall)!="id"], type_s="full")
p_overll_cluster <- function_rand(df_overll_cluster,  type_s="full")
p_overll_cluster_combined <- function_rand(df_overll_cluster_combined, type_s="upper", add_text="grey")

# pdf(file = "Figures/Clustering-comparison-All-Voom-SNM.pdf", width = 12, height = 12)
p_all
# dev.off()

# pdf(file = "Figures/Clustering-comparison-Overall-Voom-SNM.pdf", width = 8, height = 8)
p_overll_cluster
# dev.off()

# pdf(file = "Figures/Clustering-comparison-Overall_Combined-Voom-SNM.pdf", width = 8, height = 8)
p_overll_cluster_combined
# dev.off()
```


### Visualize the clusters based on overall microbiota
```{r}
df_cluster_overall <- df_cluster_overall[order(df_cluster_overall$Without_combined), ]
df_cluster_show <- df_cluster_overall[,2:6]

plot_cluster <- ComplexHeatmap::Heatmap(as.matrix(df_cluster_show),
                                        width = ncol(df_cluster_show)*unit(3, "mm"),
                                        height = nrow(df_cluster_show)*unit(2, "mm"),
                                       col = c("#0072B5CC","#E18727CC"),
                                       heatmap_legend_param = list(title="Clusters",at=c(1,2),labels=c("MS1","MS2")),
                                       column_dend_height = unit(10, "mm"),
                                       rect_gp = gpar(col = "white"),
                                       row_names_gp = gpar(fontsize=10),
                                       column_names_gp = gpar(fontsize=10),
                                       border=NA,
                                       cluster_columns = FALSE,
                                       cluster_rows = FALSE,
                                       show_row_names = FALSE,
                                       column_names_side = "top",
                                       column_names_rot = 90)

# pdf(file = "Figures/Clustering-comparison-Overall_Individuals_Combined-Voom-SNM.pdf",height = 10,width = 5)
plot_cluster
# dev.off()
```

