---
title: "03_clustering_whole"
author: "Yuqing Li"
date: "2025-05-21"
output: html_document
---

### Load requirements

```{r, message=FALSE,warning=FALSE}
{
  library(cluster)
  library(survival)
  library(survminer)
  library(tidyverse)
  library(glmnet)
  library(ape)
  library(vegan)
  library(magrittr)
  library(microbiome)
  library(caret)
  library(picante)
  library(randomForest)
  library(ROCR)
  library(Matrix)
  library(UpSetR)
  library(plotROC)
  library(pROC)
  library(gridExtra)
  library(Rmisc)
  library(timeROC)
  library(ggthemes)
  library(gridExtra)
  library(openxlsx)
  library(forestploter)
  library(tableone)
  library(broom)
  library(sjPlot)  # 输出三线表
  library(gtsummary)  # 一步输出cox结果
  library(VennDiagram)
  library(ggvenn)
  library(tinyarray)
  library(cols4all)
  library(ggsci)
  library(bootnet)
  library(igraph)
  library(qgraph)
  library(ggsci)
  library(compositions)
  library(fpc)
  library(openxlsx)
  library(corrplot)
  library(patchwork)
}
```

### Load data
```{r, message=FALSE,warning=FALSE}
# clinical data
df_meta_acc_tcga <- read.csv("./00_data_preparation/metadata.csv") %>% 
  filter(COHORT=='TCGA')

# input microbial matrix
fun_matrix_transfer <- function(matrix,method=c('com','com_filter','clr','clr_filter')){
  
  # matrix :otu*sample
  
  matrix_com <- matrix %>% 
    # dplyr::filter(rowSums(.) > 0) %>% 
    select_if(~ sum(.) > 0) %>%
    microbiome::transform("compositional") %>%   
    t()  
  
  matrix_com_filter <- matrix_com %>% 
    .[,colMeans(.> 0) > 0.05] %>%  
    as.matrix()  
  
  if(method=='com'){
    matrix_transfer <- matrix_com
  }else if(method=='com_filter'){
    matrix_transfer <- matrix_com_filter
  }else if(method=='clr'){
    matrix_clr <- matrix_com+1e-05
    matrix_clr <- matrix_clr %>% 
      compositions::clr() %>%  
      as.matrix()
    matrix_transfer <- matrix_clr
  }else {
    matrix_clr_filter <- matrix_com_filter+1e-05
    matrix_clr_filter <- matrix_clr_filter %>% 
      compositions::clr() %>%  
      as.matrix()
    matrix_transfer <- matrix_clr_filter
  }
  
  return(matrix_transfer) #sample*otu
  
}

df1 <- read.xlsx('./00_data_preparation/otu_genus_count_table.xlsx',sheet = 1,rowNames = TRUE)  %>%  mutate(across(where(is.character), as.numeric))
df2 <- read.xlsx('./00_data_preparation/otu_genus_count_table.xlsx',sheet = 2,rowNames = TRUE) %>% mutate(across(where(is.character), as.numeric))

df_otu_genus_tcga_z <- fun_matrix_transfer(df1,method = 'clr');dim(df_otu_genus_tcga_z)
df_otu_genus_tcga_s <- fun_matrix_transfer(df2,method = 'clr');dim(df_otu_genus_tcga_s)

```

### Determine the optimal number of clusters
```{r, message=FALSE,warning=FALSE}
# compute the combined metric of BC and UU from Shi et al. (DOI: 10.1186/s40168-021-01199-3)
function_dist <- function(in_matrix, dist=c("combined", "bray", "jaccard",'euclidean')){
  combMetric<-function(bray,uu,alpha=0.5){
    bray<-as.matrix(bray)
    uu<-as.matrix(uu)
    bray<-bray/max(bray)
    uu<-uu/max(uu)
    combined<-(1-alpha)*bray+alpha*uu
    rownames(combined)<-rownames(bray)
    colnames(combined)<-colnames(bray)
    combined<-as.dist(combined)
    combined
  }
  # in_matrix[in_matrix<0] <- 0 # assign zero to negative values 
  dist_br <- vegan::vegdist(in_matrix, method = "bray")
  dist_UU <- vegan::vegdist(in_matrix, method = "jaccard")
  dist_com <- combMetric(dist_br, dist_UU, alpha=0.5)
  dist_ed <- vegan::vegdist(in_matrix, method = "euclidean")
  if (dist=="combined"){return(dist_com)}
  else if (dist=="bray"){return(dist_br)}
  else if (dist=="jaccard"){return(dist_UU)}
  else {return(dist_ed)}
}

# determine the optimal number of clusters using different distance
function_optimal <- function(df1, df2, dist=c("combined", "bray", "jaccard",'euclidean')){
  if (dist=="combined"){
    dist_genus_tcga_z <- function_dist(df1, dist = "combined")
    dist_genus_tcga_s <- function_dist(df2, dist = "combined")
    
  }else if (dist=="bray"){
    dist_genus_tcga_z <- function_dist(df1, dist = "bray")
    dist_genus_tcga_s <- function_dist(df2, dist = "bray")
    
  }else if (dist=="jaccard"){
    dist_genus_tcga_z <- function_dist(df1, dist = "jaccard")
    dist_genus_tcga_s <- function_dist(df2, dist = "jaccard")
   
  }else{
    dist_genus_tcga_z <- function_dist(df1, dist = "euclidean")
    dist_genus_tcga_s <- function_dist(df2, dist = "euclidean")
   
  }
  
  function_assess <- function(in_dist, id){
    df_si <- data.frame()
    
    # Average silhouette width
    for (k in 2:10){
      pam_x <- pam(in_dist, k, diss=TRUE, keep.diss=FALSE, keep.data=FALSE)
      df_temp <- data.frame(ncluster=k, silinfo=pam_x$silinfo$avg.width)
      df_si <- rbind(df_si, df_temp)
    }
    
    # Prediction strength
    ps <- prediction.strength(in_dist, Gmin=2, Gmax=10, clustermethod=claraCBI, classification="centroid", distances=TRUE)
    df_ps <- data.frame(ncluster=1:10, predictionS=ps$mean.pred)
    df_m <- merge(df_si, df_ps, by="ncluster", all.x = TRUE)
    df_m$class <- id
    return(df_m)
  }
  
  df_ass_genus_tcga_z <- function_assess(dist_genus_tcga_z, "TCGA_Z_Genus")
  df_ass_genus_tcga_s <- function_assess(dist_genus_tcga_s, "TCGA_S_Genus")
  
  
  df_ass_bind <- rbind(df_ass_genus_tcga_z, df_ass_genus_tcga_s)
  df_ass_bind_melt <- reshape2::melt(df_ass_bind, id=c("ncluster", "class"))
  df_ass_bind_melt$variable <- as.character(df_ass_bind_melt$variable)
  df_ass_bind_melt$variable[df_ass_bind_melt$variable=="silinfo"] <- "Average silhouette width"
  df_ass_bind_melt$variable[df_ass_bind_melt$variable=="predictionS"] <- "Prediction Strength"
  
  p_ass <- ggplot(df_ass_bind_melt, aes(x=ncluster)) + 
    geom_point(aes(y = value, color=class), size=2)+
    geom_line(aes(y = value, color=class))+
    facet_wrap(~ variable, ncol = 2)+
    theme_bw()+
    scale_color_npg()+
    theme(strip.text=element_text())+
    xlab("Number of clusters")+
    ylab("")
  return(p_ass)
}

p_cluster_euclidean <-  function_optimal(df_otu_genus_tcga_z, df_otu_genus_tcga_s, dist="euclidean")

# pdf(file = "./clustering/whole/pam/Determine_optimal_cluster_number.pdf", width = 7, height = 4)
p_cluster_euclidean + ggtitle("Euclidean")
# dev.off()
```

### Check association between cluster and survival
```{r, message=FALSE,warning=FALSE}
function_sur_pam <- function(in_matrix, dist_s=c('euclidean'),endpoint=c('OS','PFS')){
  
  dist_in <- function_dist(in_matrix, dist=dist_s)
  
  # group into 2 cluster
  set.seed(123)
  pam_x <- pam(as.matrix(dist_in), 2, diss=TRUE, keep.diss=FALSE, keep.data=FALSE)
  
  df_cluster <- pam_x$clustering %>% as.data.frame() %>% setNames("Cluster_PAM")
  df_cluster$PATIENT_ID <- rownames(df_cluster)
  
  if(endpoint=='OS'){
    df_meta_ACC_m <- merge(df_meta_acc_tcga[, c("PATIENT_ID", "OS_Months", "OS_Status")], df_cluster, by="PATIENT_ID", all.x = TRUE)
    fit <- survfit(Surv(OS_Months, OS_Status) ~ Cluster_PAM, data = df_meta_ACC_m)
  }else{
    df_meta_ACC_m <- merge(df_meta_acc_tcga[, c("PATIENT_ID", "PFS_Months", "PFS_Status")], df_cluster, by="PATIENT_ID", all.x = TRUE)
    fit <- survfit(Surv(PFS_Months, PFS_Status) ~ Cluster_PAM, data = df_meta_ACC_m)
  }
  
  p <- ggsurvplot(fit,
                  data = df_meta_ACC_m,
                  conf.int = TRUE,
                  pval = TRUE,
                  palette = c("#0072B5CC","#E18727CC"),
                  xlab = "Time (Monthes)", 
                  # legend = "right",
                  legend.title = "",
                  ggtheme = theme_base(),
                  break.x.by = 40)
  return(list(df_meta_ACC_m, p))
}

for (x in c('euclidean')){
  
  #x = "combined"
  for (j in c('OS','PFS')) {
    list_genus_tcga_z <- function_sur_pam(df_otu_genus_tcga_z, dist_s = x,endpoint = j)
    list_genus_tcga_s <- function_sur_pam(df_otu_genus_tcga_s, dist_s = x,endpoint = j)
    
    
    # pdf(file = paste("./clustering/whole/pam/Determine_Clustering_AND_Survival_",x,"_",j,".pdf", sep = ""), width = 8, height = 4)
    p1 <- list_genus_tcga_z[[2]] + ggtitle(paste0(j,'_Genus_tcga_z'))
    p2 <- list_genus_tcga_s[[2]] + ggtitle(paste0(j,'_Genus_tcga_s'))
    
    res <- list(p1$plot,p2$plot)
    grid.arrange(grobs=res,ncol=2)
    # dev.off()
    
    df_genus_tcga_z <- list_genus_tcga_z[[1]] %>% dplyr::select(c("PATIENT_ID", "Cluster_PAM")) %>% setNames(c("PATIENT_ID", paste("genus_tcga_z_",x,sep = "")))
    df_genus_tcga_s <- list_genus_tcga_s[[1]] %>% dplyr::select(c("PATIENT_ID", "Cluster_PAM")) %>% setNames(c("PATIENT_ID", paste("genus_tcga_s_",x,sep = "")))
    
  }
  
  df_clustering <- Reduce(function(x,y){merge(x,y,by="PATIENT_ID", all.x=TRUE)},
                          list(df_genus_tcga_z, df_genus_tcga_s))
  df_cluster_all <- df_clustering 

}

# write.csv(df_cluster_all, file="./clustering/whole/pam/Unsupervised_clustering.csv", row.names = FALSE)
```

### Clusters_diversity
```{r, message=FALSE,warning=FALSE}
df_cluster_all <- read.csv(file = './clustering/whole/pam/Unsupervised_clustering.csv',header = TRUE)
df1 <- read.xlsx('./00_data_preparation/otu_genus_count_table.xlsx',sheet = 1,rowNames = TRUE)  %>%  mutate(across(where(is.character), as.numeric))
df2 <- read.xlsx('./00_data_preparation/otu_genus_count_table.xlsx',sheet = 2,rowNames = TRUE) %>% mutate(across(where(is.character), as.numeric))
df_otu_genus_tcga_z <- fun_matrix_transfer(df1,method = 'com');dim(df_otu_genus_tcga_z)
df_otu_genus_tcga_s <- fun_matrix_transfer(df2,method = 'com');dim(df_otu_genus_tcga_s)

# beta diversity
function_PcoA <- function(in_matrix, cluster_col, title){
  distance <- vegdist(in_matrix, method = 'bray')
  pcoa <- cmdscale(distance, k = (nrow(in_matrix) - 1), eig = TRUE)
  point <- data.frame(pcoa$point)
  pcoa_eig <- (pcoa$eig)[1:2] / sum(pcoa$eig)
  
  # extract first two coordinate value
  sample_eig <- data.frame({pcoa$point})[1:2]
  sample_eig$PATIENT_ID <- rownames(sample_eig)
  names(sample_eig)[1:2] <- c('PCoA1', 'PCoA2')
  group_m <- merge(sample_eig, df_cluster_all[,c("PATIENT_ID", cluster_col)], by = "PATIENT_ID", all.x = TRUE)
  
  # PERMANOVA
  dt <- in_matrix[group_m$PATIENT_ID,]
  print(identical(rownames(dt), group_m$PATIENT_ID))
  
  group_m[,cluster_col] <- as.factor(group_m[,cluster_col])
  set.seed(555)
  adonis_result <- adonis2(as.formula(paste("dt~", cluster_col, sep = "")), group_m, permutations = 999, distance = 'bray')
  
  R2 <- round(adonis_result$R2[1], 2)
  pvalue <- round(adonis_result$`Pr(>F)`[1], 2)
  plot <- ggscatter(group_m, x= "PCoA1", y = "PCoA2",color=cluster_col,
                    ellipse = TRUE,
                    mean.point = TRUE, star.plot = TRUE,
                    ellipse.level = 0.95,
                    ggtheme = theme_minimal()) +
    labs(x = paste('PCoA1: ', round(100 * pcoa_eig[1], 2), '%'),
         y = paste('PCoA2: ', round(100 * pcoa_eig[2], 2), '%'))+
    theme_classic()+
    scale_color_manual(values = c("#0072B5CC","#E18727CC",'grey'))+
    geom_vline(xintercept = 0, color = 'gray', size = 0.4) + 
    geom_hline(yintercept = 0, color = 'gray', size = 0.4) +
    theme(panel.grid = element_line(color = 'black', linetype = 2, size = 0.1), 
          panel.background = element_rect(color = 'black', fill = 'transparent'), 
          legend.title=element_blank())+
    theme(axis.title = element_text(size = 18, colour="black"),
          axis.text = element_text(size = 16, colour = "black"),
          legend.text = element_text(size = 16))+
    annotate("text", x = -Inf, y = Inf, label = paste("\n"," PERMANOVA R2 = ",R2 ,"\n"," P ", ifelse(pvalue<0.001,'<0.001',paste0('=',pvalue)), sep = ""), hjust = 0, vjust = 1) +
    # geom_text(x=min(group_m$PCoA1), y=max(group_m$PCoA2),hjust = 0, vjust = 1, label=paste("PERMANOVA R2 = ",R2 ,"\n","P ", ifelse(pvalue<0.001,'<0.001',paste0('=',pvalue)), sep = ""))+
    ggtitle(title)
  return(plot)
}

p_nor_tcga_z <- function_PcoA(df_otu_genus_tcga_z, 'genus_tcga_z_euclidean', "TCGA_Z")
p_nor_tcga_s <- function_PcoA(df_otu_genus_tcga_s, 'genus_tcga_s_euclidean', "TCGA_S")

# pdf(file = paste("./clustering/whole/pam/beta_diversity_two_cluster.pdf", sep = ""), width = 6, height = 5)
print(p_nor_tcga_z)
print(p_nor_tcga_s)
# dev.off()

# alpha diversity
function_alpha <- function(in_matrix,cluster_col, title){
  
  otu_matrix <- in_matrix
  Shannon = vegan::diversity(otu_matrix, index = "shannon")
  Simpson = vegan::diversity(otu_matrix, index = "simpson")
  InvSimpson = vegan::diversity(otu_matrix, index = "invsimpson")
  Richness = specnumber(otu_matrix)
  Pielou = Shannon / Richness
  
  alpha_matrix <- data.frame(Shannon,Simpson,InvSimpson,Richness,Pielou) %>% 
    tibble::rownames_to_column('PATIENT_ID') %>% 
    merge(.,df_cluster_all[,c("PATIENT_ID", cluster_col)], by = "PATIENT_ID", all.x = TRUE) %>% 
    tidyr::gather(.,-c('PATIENT_ID',cluster_col),key='alpha_diversity',value="Value") %>% 
    dplyr::mutate(group=ifelse(is.na(.[,cluster_col]),NA,paste0('MS',.[,cluster_col]))) %>% 
    dplyr::mutate(group=as.factor(group)) %>% 
    na.omit()
  
  plot <- ggplot(alpha_matrix,aes(x=alpha_diversity,y=Value,color=group))+
    geom_boxplot()+
    theme_base()+
    facet_wrap( .~ alpha_diversity, scale = "free",nrow=1) +
    scale_color_manual(values = c("#0072B5CC","#E18727CC"))+
    labs(x='',y='')+
    stat_compare_means(label = 'p.format',method ='wilcox.test',hide.ns = TRUE)+
    theme(legend.title=element_blank())+
    theme(axis.title = element_text(size = 18, colour="black"),
          axis.text = element_text(size = 16, colour = "black"),
          legend.text = element_text(size = 16))+
    ggtitle(title)
  return(plot)
}

p_alpha_tcga_z <- function_alpha(df_otu_genus_tcga_z, 'genus_tcga_z_euclidean', "TCGA_Z")  
p_alpha_tcga_s <- function_alpha(df_otu_genus_tcga_s, 'genus_tcga_s_euclidean', "TCGA_S")    

# pdf(file = paste("./clustering/whole/pam/alpha_diversity_two_cluster.pdf", sep = ""), width = 10, height = 5)
print(p_alpha_tcga_z)
print(p_alpha_tcga_s)
# dev.off()
```
